apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: final
  labels:
    app: employees
    version: v1
spec:
  selector:
    app: employees
  type: NodePort
  ports:
  - port: 81
    targetPort: 81
    nodePort: 30000
