apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: final
  labels:
    app: employees
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: app-employees
          image: 108561850742.dkr.ecr.us-east-1.amazonaws.com/application:latest
          ports:
            - containerPort: 81
          env:
            - name: DBHOST
              value: "mysql-service.final.svc.cluster.local"
            - name: DBPORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DBPORT
            - name: APP_COLOR
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_COLOR
            - name: DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATABASE
            - name: BACKGROUND_IMAGE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BACKGROUND_IMAGE_URL
            - name: GROUP_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: GROUP_NAME
            - name: GROUP_SLOGAN
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: GROUP_SLOGAN
            - name: AWS_REGION
              value: "us-east-1"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_SESSION_TOKEN
            - name: DBUSER
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: DBUSER
            - name: DBPWD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: DBPWD
