apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: final
  labels:
    app: employees
    version: v1
spec:
  selector:
    app: employees
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 81
