apiVersion: v1
kind: Secret
metadata:
  name: flask-secrets
  namespace: final
type: Opaque
stringData:
  DB_USERNAME: "admin"
  DB_PASSWORD: "admin123"
  AWS_ACCESS_KEY_ID: "ASIA2YVKQFQWD55BH2GG"
  AWS_SECRET_ACCESS_KEY: "irEQZXwO7vR1bICZNLvBLjX0dUdAbtX/k/Jc6YcK"
